Js production builds
generationtux/brizo pull request #17
Opened 2016-12-12 20:45 UTC by kyleferguson

- split routes to `root` and `api`, where API routes represent the versioned Brizo core API with a prefixed path of `/api` for the current version.

- refactor webpack builds to support both development (using webpack-dev-server) and production builds

- moved all current Go routes to the `root` router. My opinion is the oauth endpoints aren't really apart of our versioned Brizo API, but this is debatable and I'm open to discuss

- removed the hash URL scheme for the JS ui (`/app/#login`) for more standardized URLs (`/app/login`)

- setup editorconfig for JS/TS files for common standard (indent 2 spaces)

2016-12-12 21:23 UTC, larkmullins commented on ui/src/app/app.module.ts
> +        RouterModule.forRoot(routes),
How will removing useHash be used in conjunction with the API? Will routes need to be added just to Go and not Angular?

2016-12-12 21:25 UTC, kyleferguson commented on ui/src/app/app.module.ts
> +        RouterModule.forRoot(routes),
Any route that's for the UI should be handled by Angular. Go is configured to forward any route prefixed with `/app` to Angular, and Angular is configured to use `/app` as its base. So in Angular if you create a route `login`, the actual URL will be `/app/login`, and you won't need to add anything to Go because Go is already set to forward `app/*` to the Angular app.

All other routes that aren't `app/*` are handled by Go

2016-12-13 14:30 UTC, jlaswell commented on ui/config/karma-test-shim.js
> +Error.stackTraceLimit = Infinity;
Setting a limit to `Infinity` seems dangerous...

2016-12-13 14:32 UTC, jlaswell commented on ui/package.json
> +    "@angular/common": "~2.3.0",
These can all be moved to `dev-dependencies` with webpack.

2016-12-13 14:35 UTC, jlaswell requested changes
Really like the way you've split up the routing code. Just a couple comments to address.

2016-12-13 15:00 UTC, kyleferguson commented on ui/config/karma-test-shim.js
> +Error.stackTraceLimit = Infinity;
Yea I actually didn't see that, the testing setup was pretty much a copy paste from the example setup.

2016-12-13 15:10 UTC, jlaswell approved these changes

2016-12-13 15:20 UTC, merged