hooking everything together
generationtux/brizo pull request #28
Opened 2016-12-16 01:22 UTC by kyleferguson

2016-12-16 15:08 UTC, kyleferguson commented
Basic design added, ready for demo :)
![brizo-design](https://cloud.githubusercontent.com/assets/4224075/21267256/9a7e51ae-c377-11e6-9e51-b0117488a8bb.gif)

2017-01-03 15:32 UTC, jlaswell requested changes

2017-01-03 15:32 UTC, jlaswell commented on .env.example
> +OAUTH_GITHUB_CLIENT_SECRET=cddd23dc61e6faa0b1d28233d9e9b958272757ad
Committed the Client Id and Secret here.

2017-01-03 15:32 UTC, jlaswell commented on ui/src/app/dashboard/dashboard.component.ts
> +import { Component, OnInit } from '@angular/core';
Unused import

2017-01-03 15:44 UTC, kyleferguson commented on .env.example
> +OAUTH_GITHUB_CLIENT_SECRET=cddd23dc61e6faa0b1d28233d9e9b958272757ad
Intentional. I setup a `brizo-dev` application for gentux for dev simplicity. Probably bad practice for a public repo but figured we could change it easily if it becomes an issue.

2017-01-03 15:45 UTC, jlaswell commented
lgtm

2017-01-03 15:50 UTC, jlaswell approved these changes

2017-01-03 15:50 UTC, merged